### ISSUE TITLE
Push Version 1.3.2 to CF-Community-Repo

### ISSUE THREAD

**Issue by stephanabel** [dawu415/CF-CLI-Create-Service-Push-Plugin#15]
Hi there,

would it be possible to get the latest version to the Community-Repo?
Currently there is only version 1.3.1 which is not compatible with cf7.

Thanks & Best Regards,
Stephan

**Comment by dawu415** [comment]
Work in progress :)

**Comment by chgeo** [comment]
Any news here?  Isn't this blocking everyone who has cf7 and want to use the plugin?

**Comment by dawu415** [comment]
It shouldn't block them because there's a release available with the fix:

https://github.com/dawu415/CF-CLI-Create-Service-Push-Plugin/releases/tag/1.3.2

In the community repo, I am just adding the links there to point to the above release.  
See PR: https://github.com/cloudfoundry/cli-plugin-repo/pull/385

They do some checks, like naming conventions, which was already ironed out in the very early releases a long time ago.

**Comment by chgeo** [comment]
Ok thanks, I could install the plugin from the release 1.3.2

**Comment by LotharBender** [comment]
Seems that version 1.3.2 still did not reach the Community-Repo - any news here?
Thanks
Lothar

**Comment by dawu415** [comment]
Sorry - still awaiting on some information.

This project is still alive and maintained and 1.3.2 can be downloaded https://github.com/dawu415/CF-CLI-Create-Service-Push-Plugin/releases/tag/1.3.2

Please feel free to submit any other issues, PRs or feature requests.

**Comment by dawu415** [comment]
Sorry for the delays (CLA related).  This has been resolved and merged into Community Repo

https://github.com/cloudfoundry/cli-plugin-repo/pull/394

Closing this issue now.
