### ISSUE TITLE
How can you create cups?

### ISSUE THREAD

**Issue by pbaletkeman** [dawu415/CF-CLI-Create-Service-Push-Plugin#3]
How could I create a cups like the two listed below using your plugin:
- cf cups newrelic -p '{"licenseKey":"MyHiddenKeyHere"}'
- cf cups my-logs -l syslog-tls://server.papertrailapp.com:[port]

I've tried providing the extra values as parameters however I get the following error message 

> Create Service Error: Invalid configuration provided for -c flag. Please provide a valid JSON object or path to a file containing a valid JSON object.

**Comment by dawu415** [comment]
Cool - the plugin will need to be updated to support this. Currently, it only works with brokered services. It is doable and from a quick glance, it will probably need another yaml section for user provided services with a type field to simplify the code.  Will be in a remote location without laptop for several days, so will not be able to work on this.  Otherwise, pull requests are welcome :-)

**Comment by pbaletkeman** [comment]
It's great that this sounds feasible to you. I do not currently have the time to learn how to program in Go, but in I few months I may.

**Comment by dawu415** [comment]
I have created a pre-release to support CUPS, please have a try and let me know how you go. 

Example manifest in the link below

https://github.com/dawu415/CF-CLI-Create-Service-Push-Plugin/releases/tag/1.1.0-beta

Thanks!

**Comment by dawu415** [comment]
Released as 1.1.0
